---
# Try to setup repos using yum-config module if available
use_yum_config_module: true
default_compose_url: >-
  {%- if (ansible_distribution_major_version is version('8','==')) -%}
  https://composes.centos.org/latest-CentOS-Stream-8/compose/
  {%- else -%}
  https://odcs.stream.centos.org/production/latest-CentOS-Stream/compose/
  {%- endif -%}
compose_url: >-
  {{
    centos_compose_url |
      default(job.centos_compose_url) |
      default(default_compose_url)
  }}
compose_repo_variants:
  common:
    - AppStream
    - BaseOS
    - HighAvailability
  centos_stream_8:
    - PowerTools
  centos_stream_9:
    - CRB

compose_repo_variants_list:  "{{
  compose_repo_variants['common'] +
  compose_repo_variants['centos_stream_' +
                        ansible_distribution_major_version]
}}"

compose_repo_disable_repos:
  common:
    - quickstart-centos-appstreams.repo
    - quickstart-centos-base.repo
    - quickstart-centos-highavailability.repo
  centos_stream_8:
    - quickstart-centos-powertools.repo
  centos_stream_9:
    - quickstart-centos-crb.repo

compose_repo_disable_repos_list: "{{
  compose_repo_disable_repos['common'] +
  compose_repo_disable_repos['centos_stream_' +
                             ansible_distribution_major_version]
}}"

# remove '.repo' to get a dependency_override_repos list
dependency_override_repos: "{{ compose_repo_disable_repos_list | map('regex_replace', '.repo$', '') | list }}"

add_repos:
  - type: compose_repos
    compose_url: "{{ compose_url }}"
    release: centos-stream-{{ ansible_distribution_major_version }}
    disable_conflicting: true
    variants: "{{ compose_repo_variants_list }}"
    disable_repos: "{{ compose_repo_disable_repos_list }}"
