release: master
distro_ver: centos9
dlrn_hash_tag: current-tripleo
docker_image_tag: "{{ dlrn_hash|default(dlrn_hash_tag) }}"
dlrn_baseurl: "https://trunk.rdoproject.org/{{ distro_ver }}-{{ release }}"
ipa_image_url: "https://images.rdoproject.org/{{ distro_ver }}/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/ironic-python-agent.tar"

docker_registry_host: quay.rdoproject.org
docker_registry_namespace: tripleomastercentos9

overcloud_as_undercloud: true
whole_disk_images: true
update_images: true

libvirt_session_socket: virtqemud-sock

overcloud_image: >-
  {% if whole_disk_images|bool -%}
  overcloud-hardened-uefi-full
  {%- else -%}
  overcloud-full
  {%- endif -%}
overcloud_image_type: >-
  {% if whole_disk_images|bool -%}
  qcow2
  {%- else -%}
  tar
  {%- endif -%}
overcloud_image_url: "https://images.rdoproject.org/{{ distro_ver }}/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/{{ overcloud_image }}.{{ overcloud_image_type }}"

# overcloud-hardened-uefi full can't currently be used as undercloud base
undercloud_base_image: overcloud-full
undercloud_base_image_type: tar
undercloud_base_image_url: "https://images.rdoproject.org/{{ distro_ver }}/{{ release }}/rdo_trunk/{{ dlrn_hash|default(dlrn_hash_tag) }}/{{ undercloud_base_image }}.{{ undercloud_base_image_type }}"

images:
  - name: "{{ overcloud_image }}"
    url: "{{ overcloud_image_url }}"
    type: "{{ overcloud_image_type }}"
  - name: "{{ undercloud_base_image }}"
    url: "{{ undercloud_base_image_url }}"
    type: "{{ undercloud_base_image_type }}"
  - name: ipa_images
    url: "{{ ipa_image_url }}"
    type: tar

repos:
  - type: file
    filename: delorean.repo
    down_url: "https://trunk.rdoproject.org/{{ distro_ver }}-{{ release }}/{{ dlrn_hash_tag }}/delorean.repo"

  - type: file
    filename: delorean-deps.repo
    down_url: https://trunk.rdoproject.org/{{ distro_ver }}-{{ release }}/delorean-deps.repo

  - type: generic
    reponame: quickstart-centos-base
    filename: quickstart-centos-base.repo
    baseurl: http://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/

  - type: generic
    reponame: quickstart-centos-appstreams
    filename: quickstart-centos-appstreams.repo
    baseurl: http://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/

  - type: generic
    reponame: quickstart-centos-crb
    filename: quickstart-centos-crb.repo
    baseurl: http://mirror.stream.centos.org/9-stream/CRB/x86_64/os/

  - type: generic
    reponame: quickstart-centos-highavailability
    filename: quickstart-centos-highavailability.repo
    baseurl: http://mirror.stream.centos.org/9-stream/HighAvailability/x86_64/os/


repo_cmd_after: |
  sudo dnf repolist;
  sudo dnf module list;
  {% if repo_setup_run_update|default(true)|bool %}
  sudo dnf update -y
  {% endif %}

undercloud_rpm_dependencies: >-
  python3-tripleoclient
  tripleo-operator-ansible
