##########################################################
# FEATURESET053 - TRIPLEO ANSIBLE STANDALONE ROLES TESTING
##########################################################

non_root_user_setup: true
ovb_setup_connectivity: false
package_installs: true
vxlan_networking: false
toci_vxlan_networking: false
enable_vbmc: false
deploy_supplemental_node: false
undercloud_setup: true

# role / scenario definition
# deployment role
standalone_role: Standalone.yaml
standalone_libvirt_type: "{{ standalone_virt_type|default('qemu') }}"
standalone_container_cli: podman

# custom env files
standalone_custom_env_files:
  - /usr/share/openstack-tripleo-heat-templates/environments/low-memory-usage.yaml
overcloud_templates_path: /usr/share/openstack-tripleo-heat-templates

# standalone vars for compute node
neutron_public_interface_name: eth0
tripleo_network_config_template: templates/ci/multinode.j2
ctlplane_dns_nameservers:
  - 192.168.24.1
