composable_scenario: multinode-containers-mixed-os.yaml
composable_services: false

network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
containerized_overcloud: true

containerized_undercloud: true

undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates
undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

mixed_os: true

# downstream job needs pin for NovaHWMachineType
extra_args: >-
   {% if ansible_distribution in ["RedHat"] and osp_release|default('') in ['rhos-17.1'] -%}
   -e {{ overcloud_templates_path }}/ci/environments/ovb-ha-parameter-for-rhel8.yaml
   {% endif %}
   --disable-protected-resource-types --baremetal-deployment

composable_roles: true

overcloud_roles_mixed:
  - name: Controller
    CountDefault: 1
    tags:
      - primary
      - controller
  - name: Compute
    CountDefault: 1
    HostnameFormatDefault: '%stackname%-compute-%index%'
    tags:
      - compute

deployed_server: true
deploy_steps_ansible_workflow: true

config_download_args: >-
  -e {{ working_dir }}/config-download.yaml
  --disable-validations
ephemeral_heat: true
ephemeral_heat_args: "{{ '--heat-type pod' if ephemeral_heat|bool else '' }}"

# Tempest configuration, keep always at the end of the file
test_ping: false
# tempest_ping_router https://bugs.launchpad.net/tripleo/+bug/1981322
tempest_ping_router: false

# Settings for os_tempest

use_os_tempest: true

tempest_allowed_group: "featureset066"

# https://launchpad.net/bugs/1844446
undercloud_enable_validations: false

undercloud_parameter_defaults_args: >-
  {'IronicIPXEUefiSnpOnly': 'true'}
