##################################################
# FEATURESET052 - TRIPLEO STANDALONE
##################################################

non_root_user_setup: true
ovb_setup_connectivity: false
package_installs: true
vxlan_networking: false
toci_vxlan_networking: false
enable_vbmc: false
deploy_supplemental_node: false
undercloud_setup: true

# role / scenario definition
# deployment role
standalone_role: Standalone.yaml

# custom env files
standalone_custom_env_files:
  - /usr/share/openstack-tripleo-heat-templates/environments/low-memory-usage.yaml

# validation

test_ping: false
# Running only smoke tests and a few scenarios
test_white_regex: '\[.*\bsmoke\b.*\]'
# NOTE(aschultz): containers assume RC at the moment
tempest_undercloud: true
tempest_overcloud: false
tempest_workers: 2
tempest_os_cloud: standalone

tempest_allowed_group_check: "featureset052"
tempest_allowed_group_periodic: "featureset052_periodic"

# Settings for os_tempest
use_os_tempest: >-
  {% if job.skip_os_tempest is defined and job.skip_os_tempest | default(false) | bool -%}
  false
  {%- else -%}
  true
  {%- endif -%}

tempest_allowed_group: >-
  {% if (('periodic' in zuul.pipeline and not job.force_non_periodic|default(false)|bool) or (job.force_periodic|default(false)|bool)) and not tempest_run_skipped | default(false) | bool or (job.component is defined|default(false)|bool) -%}
  {{ tempest_allowed_group_periodic }}
  {%- else -%}
  {{ tempest_allowed_group_check }}
  {%- endif -%}

tempest_run_concurrency: 2
standalone_container_cli: podman
