#######################################
# FEATURESET061 - Undercloud + Minion #
#######################################

extra_args: ''

network_isolation: false
enable_pacemaker: false
overcloud_ipv6: false
undercloud_check_sanity: true

# containers config
containerized_overcloud: false
containerized_undercloud: true
undercloud_templates_path: /usr/share/openstack-tripleo-heat-templates
undercloud_custom_env_files: "{{ working_dir }}/undercloud-parameter-defaults.yaml"
undercloud_cloud_domain: "localdomain"
undercloud_undercloud_hostname: "undercloud.{{ undercloud_cloud_domain }}"
# TODO(aschultz): fix with ssl
# undercloud_undercloud_public_host: "{{ ansible_fqdn }}-unique"
# tripleo_set_unique_hostname: true

# turn off image prep
step_overcloud_image: false
step_glance_upload: false
step_register: false
step_root_device_size: false
step_root_device_hints: false
step_introspect: false

# TODO(aschultz): enable ssl once it works
# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false
undercloud_enable_swift_encryption: false

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-deploy
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - tempest-setup

  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-deploy
    - overcloud-custom-tht-script
    - overcloud-prep-containers
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - tempest-setup

# Tempest configuration, keep always at the end of the file
test_ping: false
test_regex: ''

tempest_undercloud: true
tempest_overcloud: false
# Since tripleo-ci-centos-8-containers-undercloud-minion job is only runs for train
# and will be removed in future. Below default tempest tests group does not run in this job.
tempest_allowed_group: "featureset061"

minion_container_cli: podman
