---
- name: print out dlrn, release, distro info
  debug:
    msg:
      - "the tq release is: {{ release }}"
      - "the distro is: {{ distro_ver }}"
      - "dlrn_hash is: {{ dlrn_hash }}"

- name: print out dlrn (current) newest / latest
  debug:
    msg:
      - "dlrn current: {{ dlrn_hash_newest }}"
  when: dlrn_hash_newest is defined
