---
- name: Check if /etc/ci/mirror_info.sh exists
  stat:
    path: "/etc/ci/mirror_info.sh"
  register: ci_result

- name: Make sure /etc/ci dir exists on the qcow2 image
  include_role:
    name: modify-image
    tasks_from: libguestfs.yml
  vars:
    image_to_modify: "{{ repo_inject_image_path }}"
    modify_image_upload_files:
      - src: /etc/ci/mirror_info.sh
        dest: /etc/ci/mirror_info.sh
    modify_image_run_command: "'mkdir -p /etc/ci'"
  when:
    - ci_result.stat.exists
    - repo_inject_image_path.endswith('qcow2')

- name: Inject the repositories into the image
  include_role:
    name: modify-image
  vars:
    image_to_modify: "{{ repo_inject_image_path }}"
    modify_script: "{{ repo_setup_dir }}/{{ repo_setup_script }}"
