---
# Use NODEPOOL_RDO_PROXY if set else default using dlrn_baseurl
# https://trunk.rdoproject.org or http://osp-trunk.hosted.upshift.rdu2.redhat.com
- name: extract NODEPOOL_RDO_PROXY from bash environment
  shell: |
    if [ -e /etc/ci/mirror_info.sh ]; then
      source /etc/ci/mirror_info.sh
    fi
    default_dlrn="{{ dlrn_baseurl|urlsplit('scheme') }}://{{ dlrn_baseurl|urlsplit('hostname') }}"
    NODEPOOL_RDO_PROXY=${NODEPOOL_RDO_PROXY:-$default_dlrn}
    echo $NODEPOOL_RDO_PROXY
  register: nodepool_rdo_proxy_result
  failed_when: false
  changed_when: false

- name: "set fact with NODEPOOL_RDO_PROXY {{ nodepool_rdo_proxy_result.stdout }} "
  set_fact:
    nodepool_rdo_proxy: "{{ nodepool_rdo_proxy_result.stdout }}"
